---
- name: get size of devices in bytes
  become: yes
  command: blockdev --getsize64 {{ device_fullname }}
  changed_when: False
  register: comm_res

- name: populate the map of device to its size
  set_fact:
    # see Combining hashes/dictionaries
    #   https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#combining-hashes-dictionaries
    device_sizes: >
      {{ (hostvars[inventory_hostname]['device_sizes'] | default({})) | combine({ device_name: comm_res['stdout'] | int }) }}
