---
all:
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  hosts:
    localhost:
      # This user should be a sudo user.
      ansible_user: "{{ lookup('env', 'USER') }}"

      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'

  children:
    # ADD YOUR CONFIGURATIONS FOR HOSTS DOWN BELOW #
    rocksdb:
      hosts:
        # example-rocksdb-node1:
        #   # The RocksDB RMI server will bind to this IP
        #   ansible_host: 10.0.0.1

        #   # This user should be a sudo user.
        #   ansible_user: ubuntu

        #   # The names of PARENT storage devices on the initiator server.
        #   # Each storage device is assigned to a RocksDB instance for data
        #   # operations and each RocksDB instance stores data only to one
        #   # storage device.
        #   # This is required for each host.
        #   init_devices:
        #     - sda
        #     - sdb

        #   # The system available ports on the host (the device machine).
        #   # These ports are used to run RocksDB RIM servers.
        #   # Each RocksDB RMI server is only responsible for one device,
        #   # so the number of ports should be the same as the number of DUTs.
        #   # See https://github.com/ljishen/YCSB/tree/remote-rocksdb/rocksdb
        #   rmi_ports:
        #     - 1099
        #     - 1100

    storage:
      hosts:
        # example-storage-node1:
        #   ansible_host: 10.0.0.2

        #   # This user should be a sudo user.
        #   ansible_user: ubuntu

        #   # The names of PHYSICAL PARENT storage devices under test (DUT)
        #   # on the target server.
        #   # This is required for each host.
        #   # CAUTION: ALL DATA on the DUTs will be ERASED!
        #   #
        #   # You need to config the target hosts ([storage]) and the initiator hosts
        #   # ([rocksdb]) beforehand to set up connections of how the init_devices map to
        #   # the target_devices using protocols such as iSCSI or NVMe-oF.
        #   # Performance statistics will be collected from these hosts.
        #   target_devices:
        #     - sda
        #     - sdb
