---
- name: ({{ notes }}) backup local file
  copy:
    backup: yes
    content: ""
    dest: "{{ local_file }}"
    force: yes
    owner: "{{ lookup('env', 'USER') }}"
  register: copy_res
  delegate_to: localhost

- name: ({{ notes }}) fetch remote file
  fetch:
    dest: "{{ local_file }}"
    fail_on_missing: yes
    flat: yes
    src: "{{ remote_file }}"

- name: ({{ notes }}) clean backup
  shell: |
    if cmp -s {{ copy_res.backup_file }} {{ local_file }}; then
      rm --force {{ copy_res.backup_file }}
    fi
  delegate_to: localhost
  when: copy_res.backup_file is defined
...
