---
- name: "{{ '(' + notes + ') ' if notes is defined else '' }}backup local file"
  copy:
    backup: yes
    content: ''
    dest: '{{ local_file }}'
    force: yes
    owner: "{{ hostvars['localhost']['ansible_user'] }}"
  register: copy_res
  delegate_to: localhost

- name: "{{ '(' + notes + ') ' if notes is defined else '' }}fetch remote file"
  fetch:
    dest: '{{ local_file }}'
    fail_on_missing: yes
    flat: yes
    src: '{{ remote_file }}'

- name: "{{ '(' + notes + ') ' if notes is defined else '' }}clean backup"
  shell: |
    if cmp -s {{ copy_res['backup_file'] }} {{ local_file }}; then
      rm --force {{ copy_res['backup_file'] }}
    fi
  delegate_to: localhost
  when: copy_res.backup_file is defined
