---
- include_tasks: backup_file.yml
  vars:
    local_file: "{{ item.local_file }}"
    remote_file: "{{ item.remote_file }}"
  loop:
    - { local_file: "{{ local_cpustat_log_file }}",
        remote_file: "{{ remote_cpustat_log_file }}" }
    - { local_file: "{{ local_memstat_log_file }}",
        remote_file: "{{ remote_memstat_log_file }}" }
    - { local_file: "{{ local_iostat_log_file }}",
        remote_file: "{{ remote_iostat_log_file }}" }
    - { local_file: "{{ local_pidstat_log_file }}",
        remote_file: "{{ remote_pidstat_log_file }}" }
...
