---
- name: ({{ notes }}) create local backup dirs for storage sys usage info
  become: yes
  file:
    owner: "{{ lookup('env', 'USER') }}"
    path: "{{ local_storage_sys_usage_info_dir }}"
    state: directory
  vars:
    current_host: "{{ item }}"
  loop: "{{ hostvars[item]['device_names'] }}"
  loop_control:
    loop_var: device_name
  delegate_to: localhost
...
