---
- name: ensure the presence of local tmp data dir {{ local_tmp_data_dir }}
  become: yes
  local_action:
    module: file
    owner: "{{ lookup('env', 'USER') }}"
    path: "{{ local_tmp_data_dir }}"
    state: directory

- name: fetch the core workload parameter files
  fetch:
    dest: "{{ local_tmp_data_dir }}/"
    fail_on_missing: yes
    flat: yes
    src: "{{ ycsb_dir }}/workloads/{{ item }}"
  loop: "{{ core_workloads }}"
  run_once: yes

- name: ensure the presence of remote dirs
  become: yes
  file:
    owner: "{{ ansible_user }}"
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ device_mountpoint }}"
    - "{{ remote_scripts_dir }}"
    - "{{ remote_pid_files_dir }}"

- block:
    - name: get size of {{ device_fullname }} in bytes
      become: yes
      command: blockdev --getsize64 {{ device_fullname }}
      register: comm_res
      changed_when: False

    - set_fact:
        device_size: "{{ comm_res.stdout }}"

    - name: download device purge script
      become: yes
      get_url:
        backup: no
        dest: "{{ remote_scripts_dir }}/{{ device_purge_script_filename }}"
        force: yes
        mode: u+rx
        owner: "{{ ansible_user }}"
        url: https://raw.githubusercontent.com/ljishen/SSSPT/master/playbooks/roles/common/files/{{ device_purge_script_filename }}

    - name: template the workload independent pre-conditioning job file to {{ remote_job_files_dir }}
      template:
        backup: no
        dest: "{{ remote_job_files_dir }}/"
        force: yes
        owner: "{{ ansible_user }}"
        src: wipc.fio
  when: load_data

- name: kill the remnant processes for tracing block requests
  become: yes
  command: pkill -SIGINT --full blktrace.+{{ device_name }}
  ignore_errors: yes

- include_tasks: repeat_workload.yml
  vars:
    rocksdb_data_dir: "{{ device_mountpoint }}/{{ rocksdb_data_dirname }}"
    cur_workload: "{{ cur_workload_path | basename }}"
    notes: "{{ cur_workload }}"
  loop: "{{ run_workloads }}"
  loop_control:
    loop_var: cur_workload_path
...
