---
- name: ensure the presence of local tmp data dir {{ local_tmp_data_dir }}
  become: yes
  local_action:
    module: file
    owner: "{{ lookup('env', 'USER') }}"
    path: "{{ local_tmp_data_dir }}"
    state: directory

- name: fetch the core workload parameter files
  fetch:
    dest: "{{ local_tmp_data_dir }}/"
    fail_on_missing: yes
    flat: yes
    src: "{{ ycsb_dir }}/workloads/{{ item }}"
  loop: "{{ core_workloads }}"
  run_once: yes

- name: get the parent device info of device {{ device_fullname }}
  command: "{{ role_path }}/files/devname2id.sh {{ device_fullname }}"
  register: comm_res
  changed_when: False

- set_fact:
    pdevice_fullname: "{{ comm_res.stdout_lines[0] }}"
    pdevice_id: "{{ comm_res.stdout_lines[1] }}"

- include_tasks: repeat_workload.yml
  vars:
    rocksdb_data_dir: "{{ mountpoint }}/{{ rocksdb_data_dirname }}"
    cur_workload: "{{ cur_workload_path | basename }}"
    notes: "{{ cur_workload }}"
  loop: "{{ run_workloads }}"
  loop_control:
    loop_var: cur_workload_path
...
