---
- name: ensure the presence of local tmp data dir {{ local_tmp_data_dir }}
  become: yes
  local_action:
    module: file
    owner: "{{ lookup('env', 'USER') }}"
    path: "{{ local_tmp_data_dir }}"
    state: directory

- name: fetch the core workload parameter files
  fetch:
    dest: "{{ local_tmp_data_dir }}/"
    fail_on_missing: yes
    flat: yes
    src: "{{ ycsb_dir }}/workloads/{{ item }}"
  loop: "{{ core_workloads }}"
  run_once: yes

- include_tasks: repeat_workload.yml
  vars:
    cur_workload: "{{ cur_workload_path | basename }}"
    notes: "{{ cur_workload }}"
    rocksdb_data_dir: "{{ mountpoint }}/{{ rocksdb_data_dirname }}"
    local_output_dir: "{{ inventory_dir }}/analysis/data/{{ inventory_hostname }}/output_{{ cur_workload }}"
    remote_output_dir: "{{ workdir }}/data/output_{{ cur_workload }}"
    local_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"
    remote_workload_file: "{{ remote_output_dir }}/{{ cur_workload }}"
    local_rocksdb_options_file: "{{ local_output_dir }}/{{ rocksdb_options_file | basename }}"
    remote_rocksdb_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"
    output_filename: "load.dat"
    local_output_file: "{{ local_output_dir }}/{{ output_filename }}"
    remote_output_file: "{{ remote_output_dir }}/{{ output_filename }}"
  loop: "{{ run_workloads }}"
  loop_control:
    loop_var: cur_workload_path
...
