---
- name: ({{ notes }}) copy user-defined workload parameter file to {{ local_tmp_data_dir }}
  local_action:
    module: copy
    backup: yes
    dest: "{{ local_tmp_data_dir }}/"
    force: yes
    owner: "{{ lookup('env', 'USER') }}"
    remote_src: no
    src: "templates/{{ cur_workload }}"
  when: cur_workload not in core_workloads

- name: ({{ notes }}) deploy workload parameter file
  template:
    backup: yes
    dest: "{{ workloads_dir }}/{{ cur_workload }}"
    force: yes
    owner: "{{ ansible_user }}"
    src: "{{ local_tmp_data_dir }}/{{ cur_workload }}"

- name: ({{ notes }}) append common properties to parameter file
  blockinfile:
    backup: no
    block: "{{ lookup('template', 'common') }}"
    create: no
    insertafter: EOF
    owner: "{{ ansible_user }}"
    path: "{{ workloads_dir }}/{{ cur_workload }}"
    state: present

- set_fact:
    outer_notes_repeat: "{{ notes }}"

- include_tasks: do_run.yml
  vars:
    notes: "{{ outer_notes_repeat }}, round {{ cur_round }}"
  with_sequence: count={{ maximum_rounds }}
  loop_control:
    loop_var: cur_round
...
