---
# include_tasks does not propagate delegate_to to sub-tasks
# https://github.com/ansible/ansible/issues/37995
# However, wrapping include_tasks within a block can bypass
# this restriction.
- block:
    - include_tasks: "{{ tasks_filename }}"
      vars:
        current_host: "{{ item }}"
        current_ansible_user: "{{ hostvars[ansible_host]['ansible_user'] }}"
        device_name: "{{ device_fullname | basename }}"
      loop: "{{ hostvars[item]['device_fullnames'] }}"
      loop_control:
        loop_var: device_fullname
  delegate_to: "{{ item }}"
...
