---
- name: ({{ notes }}) start to collect remote system performance statistics
  # we use stdbuf to turn off the buffering of the output redirection.
  #   https://linux.die.net/man/1/stdbuf
  #   https://stackoverflow.com/a/1429973
  shell: >
    nohup stdbuf -oL -eL {{ item.command }} < /dev/null > {{ item.remote_log_file }} 2>&1 &
    echo $! > {{ item.pid_file }}
  environment:
    S_TIME_FORMAT: ISO
  vars:
    device_name: "{{ device_fullname | basename }}"
  loop:
    - { command: "{{ perf_cpustat_command }}",
        remote_log_file: "{{ rocksdb_cpustat_log_file }}",
        pid_file: "{{ rocksdb_cpustat_pid_file }}" }
    - { command: "{{ perf_memstat_command }}",
        remote_log_file: "{{ rocksdb_memstat_log_file }}",
        pid_file: "{{ rocksdb_memstat_pid_file }}" }
    - { command: "{{ perf_iostat_command }}",
        remote_log_file: "{{ rocksdb_iostat_log_file }}",
        pid_file: "{{ rocksdb_iostat_pid_file }}" }
    - { command: "{{ perf_pidstat_command }}",
        remote_log_file: "{{ rocksdb_pidstat_log_file }}",
        pid_file: "{{ rocksdb_pidstat_pid_file }}" }
    - { command: "{{ perf_netstat_command }}",
        remote_log_file: "{{ rocksdb_netstat_log_file }}",
        pid_file: "{{ rocksdb_netstat_pid_file }}" }
  changed_when: True

- name: ({{ notes }}) start to collect local system performance statistics
  shell: >
    nohup stdbuf -oL -eL {{ item.command }} < /dev/null > {{ item.remote_log_file }} 2>&1 &
    echo $! > {{ item.pid_file }}
  environment:
    S_TIME_FORMAT: ISO
  vars:
    device_name: "{{ device_fullname | basename }}"
  loop:
    - { command: "{{ perf_cpustat_command }}",
        remote_log_file: "{{ ycsb_cpustat_log_file }}",
        pid_file: "{{ ycsb_cpustat_pid_file }}" }
    - { command: "{{ perf_memstat_command }}",
        remote_log_file: "{{ ycsb_memstat_log_file }}",
        pid_file: "{{ ycsb_memstat_pid_file }}" }
    - { command: "{{ perf_pidstat_command }}",
        remote_log_file: "{{ ycsb_pidstat_log_file }}",
        pid_file: "{{ ycsb_pidstat_pid_file }}" }
    - { command: "{{ perf_netstat_command }}",
        remote_log_file: "{{ ycsb_netstat_log_file }}",
        pid_file: "{{ ycsb_netstat_pid_file }}" }
  delegate_to: localhost
  changed_when: True
...
