---
- name: ({{ notes }}) start to trace the block events for device {{ device_fullname }}
  become: yes
  shell: >
    nohup blktrace
    --act-mask=complete
    --act-mask=issue
    --buffer-size=4096KiB
    --dev={{ device_fullname }}
    --output={{ device_name }}
    --output-dir={{ remote_blkstat_log_dir }}
    --relay={{ debugfs_mountpoint }}
    < /dev/null > {{ workdir }}/nohup.out 2>&1 &
    echo $! > {{ blkstat_pid_file }}

- name: ({{ notes }}) pause to wait for the tracer to start
  pause:
    seconds: 3
...
