---
- name: ({{ notes }}) start to trace the block events for devices
  become: yes
  shell: >
    nohup blktrace
    --buffer-size=4096KiB
    --dev={{ device_fullname }}
    --output={{ device_name }}
    --output-dir={{ remote_blkstat_log_dir }}
    --relay={{ debugfs_mountpoint }}
    < /dev/null > {{ remote_nohup_output_dir }}/blkstat_nohup.out 2>&1 &
  vars:
    device_name: "{{ device_fullname | basename }}"
  loop: "{{ device_fullnames }}"
  loop_control:
    loop_var: device_fullname

- name: ({{ notes }}) pause to wait for the tracer to start
  pause:
    seconds: 5
...
