---
- name: ({{ notes }}) stop to trace block requests
  become: yes
  command: pkill -SIGINT --full blktrace.+{{ device_fullname }}
  register: comm_res
  changed_when: comm_res.rc == 0

- name: ({{ notes }}) pause to wait for the block request tracer to finish
  pause:
    seconds: 10

- name: ({{ notes }}) archive the blkstat log dir
  archive:
    dest: "{{ remote_blkstat_log_archive }}"
    format: "{{ blkstat_archive_format }}"
    owner: "{{ ansible_user }}"
    path: "{{ remote_blkstat_log_dir }}"
    remove: no

- name: ({{ notes }}) parse event streams of {{ device_fullname }} for I/O size analysis
  command: >
    blkparse
    --act-mask={{ event }}
    --input-directory={{ remote_blkstat_log_dir }}
    --input={{ device_name }}
    --output={{ remote_blkstat_text_file }}
    --per-program-stats
  vars:
    event: "{{ item }}"
  loop: [ 'issue', 'complete' ]

- include_tasks: backup_file.yml
  vars:
    local_file: "{{ local_output_dir }}/{{ blkstat_text_filename }}"
    remote_file: "{{ remote_blkstat_text_file }}"
    event: "{{ item }}"
  loop: [ 'issue', 'complete' ]

- name: ({{ notes }}) parse event streams of {{ device_fullname }} for I/O replay
  command: >
    blkparse
    --input-directory={{ remote_blkstat_log_dir }}
    --input={{ device_name }}
    --output=/dev/null
    --dump-binary={{ remote_blkstat_bin_file }}

- include_tasks: backup_file.yml
  vars:
    local_file: "{{ local_output_dir }}/{{ blkstat_bin_filename }}"
    remote_file: "{{ remote_blkstat_bin_file }}"

- name: ({{ notes }}) generate I/O size distribution
  shell: >
    {{ remote_scripts_dir }}/{{ io_size_dist_script_filename }} {{ remote_blkstat_text_file }}
    > {{ remote_ioszdist_log_file }} 2>&1
  vars:
    event: complete

- include_tasks: backup_file.yml
  vars:
    local_file: "{{ item.local_file }}"
    remote_file: "{{ item.remote_file }}"
  loop:
    - { local_file: "{{ local_output_dir }}/{{ remote_blkstat_log_archive | basename }}",
        remote_file: "{{ remote_blkstat_log_archive }}" }
    - { local_file: "{{ local_output_dir }}/{{ ioszdist_log_filename }}",
        remote_file: "{{ remote_ioszdist_log_file }}" }
...
