---
# This task wait until the related PID does not exist.
- shell: >
    pgrep --pidfile {{ pid_file }} || (rm --force {{ pid_file }} ; exit 1)
  ignore_errors: yes
  register: result
  until: result.rc != 0
  retries: "{{ (single_task_wait_duration | int) // (delay | int) }}"
  delay: "{{ delay }}"
...
