---
- name: ({{ notes }}) check the existence of the PID file
  stat:
    get_attributes: no
    get_checksum: no
    get_mime: no
    path: "{{ pid_file }}"
  register: stat_res

# This task wait until the related PID does not exist.
- name: ({{ notes }}) wait until the process is finished
  shell: |
    if pgrep --pidfile {{ pid_file }} > /dev/null 2>&1; then
        exit 1
    else
        rm --force {{ pid_file }}
    fi
  ignore_errors: yes
  register: wait_res
  until: wait_res.rc == 0
  retries: "{{ (single_task_wait_duration | int) // (delay | int) }}"
  delay: "{{ delay }}"
  changed_when: stat_res.stat.isreg is defined and stat_res.stat.isreg
...
