---
# This task wait until the related PID does not exist.
- name: wait until the process is finished
  shell: |
    if pgrep --pidfile {{ pid_file }}; then
      exit 1
    else
      rm --force {{ pid_file }}
    fi
  ignore_errors: yes
  register: result
  until: result.rc == 0
  retries: "{{ (single_task_wait_duration | int) // (delay | int) }}"
  delay: "{{ delay }}"
  changed_when: True
...
