---
rocksdb_dir: "{{ workdir }}/rocksdb-{{ rocksdb_version }}"
rocksdbjni_src: "{{ rocksdb_dir }}/java/target/rocksdbjni-{{ rocksdb_version }}-linux64.jar"
rocksdbjni_dest_dir: "{{ ansible_user_dir }}/.m2/repository/org/rocksdb/rocksdbjni/{{ rocksdb_version }}"
rocksdbjni_dest_pom: "{{ rocksdbjni_dest_dir }}/rocksdbjni-{{ rocksdb_version }}.pom"
