---
- include_tasks: run_tasks_on_host_devices.yml
  vars:
    tasks_filename: purge_single_device.yml
  loop: "{{ groups['storage'] }}"

- name: ({{ notes }}) wait purge processes to finish
  include_tasks: run_tasks_on_host_devices.yml
  vars:
    tasks_filename: wait_single_async_task.yml
    pid_file: "{{ purge_device_pid_file }}"
    delay: "{{ retry_delay_30_secs }}"
  loop: "{{ groups['storage'] }}"

- include_tasks: run_tasks_on_host_devices.yml
  vars:
    tasks_filename: run_wipc.yml
  loop: "{{ groups['storage'] }}"

- name: ({{ notes }}) check wipc status
  include_tasks: run_tasks_on_host_devices.yml
  vars:
    tasks_filename: wait_single_async_task.yml
    pid_file: "{{ wipc_pid_file }}"
    delay: "{{ retry_delay_30_secs }}"
  loop: "{{ groups['storage'] }}"

- name: ({{ notes }}) backup wipc outputs
  include_tasks: run_tasks_on_host_devices.yml
  vars:
    tasks_filename: backup_file.yml
    local_file: "{{ local_wipc_output_file }}"
    remote_file: "{{ remote_wipc_output_file }}"
  loop: "{{ groups['storage'] }}"
...
