---
- name: ({{ notes }}) purge device (using blkdiscard)
  become: yes
  command: blkdiscard --verbose {{ device_fullname }}
  register: blkdiscard_res
  changed_when: blkdiscard_res.rc == 0
  failed_when: False

- name: ({{ notes }}) purge device (using hdparm)
  become: yes
  shell: |
    nohup stdbuf -oL -eL \
        {{ scripts_dir }}/{{ discard_sectors_script_filename }} {{ device_fullname }} \
        < /dev/null \
        > {{ remote_nohup_output_dir }}/purge_device.nohup 2>&1 &
    echo $! > {{ purge_device_pid_file }}
  register: hdparm_res
  changed_when: hdparm_res is not skipped and hdparm_res.rc == 0
  when: blkdiscard_res.rc != 0
