---
- name: ({{ notes }}) purge device (using blkdiscard)
  become: yes
  command: blkdiscard --verbose {{ device_fullname }}
  register: blkdiscard_res
  changed_when: blkdiscard_res.rc == 0
  ignore_errors: yes

- name: ({{ notes }}) purge device (using hdparm)
  become: yes
  shell: >
    nohup {{ scripts_dir }}/{{ discard_sectors_script_filename }} {{ device_fullname }}
    < /dev/null > {{ remote_nohup_output_dir }}/purge_dev_nohup.out 2>&1 &
    echo $! > {{ purge_device_pid_file }}
  changed_when: True
  when: blkdiscard_res.rc != 0
...
