---
- name: ({{ notes }}) run workload independent pre-conditioning (wipc) on devices
  become: yes
  shell: >
    nohup {{ fio_bin }} {{ remote_wipc_job_file }}
    --output-format=json+
    --output {{ remote_wipc_output_file }}
    < /dev/null > {{ remote_nohup_output_dir }}/wipc_nohup.out 2>&1 &
    echo $! > {{ wipc_pid_file }}
  changed_when: True
...
