---
- name: ensure the presence of {{ software_dir }}
  become: yes
  file:
    owner: "{{ ansible_user }}"
    path: "{{ software_dir }}"
    state: directory

- name: ensure the presence of {{ scripts_dir }}
  file:
    owner: "{{ ansible_user }}"
    path: "{{ scripts_dir }}"
    state: directory

- block:
    - name: ensure the presence of {{ software_dir }}
      file:
        owner: "{{ lookup('env', 'USER') }}"
        path: "{{ software_dir }}"
        state: directory

    - name: ensure the presence of {{ scripts_dir }}
      file:
        owner: "{{ lookup('env', 'USER') }}"
        path: "{{ scripts_dir }}"
        state: directory

    - name: ensure the presence of {{ local_tmp_data_dir }}
      file:
        owner: "{{ lookup('env', 'USER') }}"
        path: "{{ local_tmp_data_dir }}"
        state: directory
  delegate_to: localhost
  become: yes
  run_once: yes

- name: ensure the presence of remote pid files dir
  become: yes
  file:
    owner: "{{ ansible_user }}"
    path: "{{ remote_pid_files_dir }}"
    state: directory
  loop: "{{ device_names }}"
  loop_control:
    loop_var: device_name

- name: ensure the presence of local pid files dir
  become: yes
  file:
    owner: "{{ lookup('env', 'USER') }}"
    path: "{{ local_pid_files_dir }}"
    state: directory
  loop: "{{ device_names }}"
  loop_control:
    loop_var: device_name
  when: inventory_hostname in groups['rocksdb']
  delegate_to: localhost

- name: ensure the presence of remote nohup output dir
  become: yes
  file:
    owner: "{{ ansible_user }}"
    path: "{{ remote_nohup_output_dir }}"
    state: directory
  loop: "{{ device_names }}"
  loop_control:
    loop_var: device_name

- name: ensure the presence of device mountpoints
  become: yes
  file:
    owner: "{{ ansible_user }}"
    path: "{{ device_mountpoint }}"
    state: directory
  loop: "{{ device_names }}"
  loop_control:
    loop_var: device_name
  when: inventory_hostname in groups['rocksdb']
...
