---
- name: check if JDK installed
  command: javac -version
  ignore_errors: yes
  register: comm_res
  changed_when: False

- block:
    - name: add WebUpd8 Oracle Java PPA
      apt_repository:
        repo: ppa:webupd8team/java
        state: present
        update_cache: yes

    - name: auto accept Oracle license
      shell: >
        echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: install JDK 8
      apt:
        install_recommends: no
        name:
          - oracle-java8-installer
        state: present
  become: yes
  when: comm_res.rc != 0

- name: download Apache Maven
  unarchive:
    creates: "{{ maven_dir }}"
    dest: "{{ software_dir }}"
    keep_newer: no
    remote_src: yes
    src: http://mirrors.advancedhosters.com/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
...
