---
# Since the YCSB RocksDB binding just combines all the fields into a single
# byte array as the value. Reducing the field counts helps to free up more CPU
# resources for the I/O path.
fieldcount: 1

# (DO NOT CHANGE) Use the last x number of values to detect steady state.
measurement_window_size: 5


rocksdb_data_dir: "{{ mountpoint }}/{{ rocksdb_data_dirname }}"

local_output_dir: "{{ inventory_dir }}/analysis/data/{{ inventory_hostname }}/output_{{ cur_workload }}"
remote_output_dir: "{{ workdir }}/data/output_{{ cur_workload }}"

local_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"
remote_workload_file: "{{ remote_output_dir }}/{{ cur_workload }}"

local_rocksdb_options_file: "{{ local_output_dir }}/{{ rocksdb_options_file | basename }}"
remote_rocksdb_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"

output_filename: "load.dat"
local_output_file: "{{ local_output_dir }}/{{ output_filename }}"
remote_output_file: "{{ remote_output_dir }}/{{ output_filename }}"

cpustat_pid_file: "{{ workdir }}/cpustat.pid"
cpustat_log_filename: "cpustat.log"
local_cpustat_log_file: "{{ local_output_dir }}/{{ cpustat_log_filename }}"
remote_cpustat_log_file: "{{ remote_output_dir }}/{{ cpustat_log_filename }}"

memstat_pid_file: "{{ workdir }}/memstat.pid"
memstat_log_filename: "memstat.log"
local_memstat_log_file: "{{ local_output_dir }}/{{ memstat_log_filename }}"
remote_memstat_log_file: "{{ remote_output_dir }}/{{ memstat_log_filename }}"

blkstat_pid_file: "{{ workdir }}/blkstat.pid"
blkstat_log_filename: "blkstat.dat"
local_blkstat_log_file: "{{ local_output_dir }}/{{ blkstat_log_filename }}"
remote_blkstat_log_file: "{{ remote_output_dir }}/{{ blkstat_log_filename }}"
