---
# Since the YCSB RocksDB binding just combines all the fields into a single
# byte array as the value. Reducing the field counts helps to free up more CPU
# resources for the I/O path.
fieldcount: 1

# (DO NOT CHANGE) Use the last x number of values to detect steady state.
measurement_window_size: 5

perf_stats_report_interval_sec: 3

rocksdb_remote_input_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"

local_rocksdb_log_file: "{{ local_output_dir }}/LOG_{{ phase }}_round{{ cur_round }}"

local_output_dir: "{{ inventory_dir }}/analysis/data/ycsb/{{ inventory_hostname }}/output_{{ cur_workload }}"
remote_output_dir: "{{ workdir }}/data/output_{{ cur_workload }}"

local_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"
remote_workload_file: "{{ remote_output_dir }}/{{ cur_workload }}"

load_filename: "load_round{{ cur_round }}.dat"
local_load_output_file: "{{ local_output_dir }}/{{ load_filename }}"
remote_load_output_file: "{{ remote_output_dir }}/{{ load_filename }}"

transactions_filename: "transactions_round{{ cur_round }}.dat"
local_transactions_output_file: "{{ local_output_dir }}/{{ transactions_filename }}"
remote_transactions_output_file: "{{ remote_output_dir }}/{{ transactions_filename }}"

cpustat_pid_file: "{{ workdir }}/cpustat.pid"
cpustat_log_filename: "cpustat.log"
local_cpustat_log_file: "{{ local_output_dir }}/{{ cpustat_log_filename }}"
remote_cpustat_log_file: "{{ remote_output_dir }}/{{ cpustat_log_filename }}"

memstat_pid_file: "{{ workdir }}/memstat.pid"
memstat_log_filename: "memstat.log"
local_memstat_log_file: "{{ local_output_dir }}/{{ memstat_log_filename }}"
remote_memstat_log_file: "{{ remote_output_dir }}/{{ memstat_log_filename }}"

iostat_pid_file: "{{ workdir }}/iostat.pid"
iostat_log_filename: "iostat.log"
local_iostat_log_file: "{{ local_output_dir }}/{{ iostat_log_filename }}"
remote_iostat_log_file: "{{ remote_output_dir }}/{{ iostat_log_filename }}"

pidstat_pid_file: "{{ workdir }}/pidstat.pid"
pidstat_log_filename: "pidstat.log"
local_pidstat_log_file: "{{ local_output_dir }}/{{ pidstat_log_filename }}"
remote_pidstat_log_file: "{{ remote_output_dir }}/{{ pidstat_log_filename }}"

blkstat_pid_file: "{{ workdir }}/blkstat.pid"
blkstat_log_filename: "blkstat_round{{ cur_round }}.dat"
remote_blkstat_log_file: "{{ remote_output_dir }}/{{ blkstat_log_filename }}"

ioszdist_log_filename: "ioszdist_round{{ cur_round }}.log"
local_ioszdist_log_file: "{{ local_output_dir }}/{{ ioszdist_log_filename }}"
remote_ioszdist_log_file: "{{ remote_output_dir }}/{{ ioszdist_log_filename }}"
