---
device_mountpoint: /mnt/{{ device_name }}

# Since the YCSB RocksDB binding just combines all the fields into a single
# byte array as the value. Reducing the field counts helps to free up more CPU
# resources for the I/O path.
fieldcount: 1

# (DO NOT CHANGE) Use the last x number of values to detect steady state.
measurement_window_size: 5

perf_stats_report_interval_sec: 3

rocksdb_remote_input_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"

local_rocksdb_log_file: "{{ local_output_dir }}/LOG_{{ phase }}_round{{ cur_round }}"

local_output_dir: "{{ inventory_dir }}/analysis/data/ycsb/{{ inventory_hostname }}/output_{{ cur_workload }}"
remote_output_dir: "{{ workdir }}/data/output_{{ cur_workload }}"

remote_scripts_dir: "{{ workdir }}/scripts"
device_purge_script_filename: blkerasediscard.sh

wipc_job_filename: wipc.fio
remote_wipc_job_file: "{{ remote_output_dir }}/{{ wipc_job_filename }}"
local_wipc_job_file: "{{ local_output_dir }}/{{ wipc_job_filename }}"

wipc_output_filename: wipc_round{{ cur_round }}.json
local_wipc_output_file: "{{ local_output_dir }}/{{ wipc_output_filename }}"
remote_wipc_output_file: "{{ remote_output_dir }}/{{ wipc_output_filename }}"

local_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"
remote_workload_file: "{{ remote_output_dir }}/{{ cur_workload }}"

load_filename: "load_round{{ cur_round }}.dat"
local_load_output_file: "{{ local_output_dir }}/{{ load_filename }}"
remote_load_output_file: "{{ remote_output_dir }}/{{ load_filename }}"

transactions_filename: "transactions_round{{ cur_round }}.dat"
local_transactions_output_file: "{{ local_output_dir }}/{{ transactions_filename }}"
remote_transactions_output_file: "{{ remote_output_dir }}/{{ transactions_filename }}"

remote_pid_files_dir: "{{ workdir }}/pid_files"

cpustat_pid_file: "{{ remote_pid_files_dir }}/cpustat.pid"
cpustat_log_filename: "cpustat.log"
local_cpustat_log_file: "{{ local_output_dir }}/{{ cpustat_log_filename }}"
remote_cpustat_log_file: "{{ remote_output_dir }}/{{ cpustat_log_filename }}"

memstat_pid_file: "{{ remote_pid_files_dir }}/memstat.pid"
memstat_log_filename: "memstat.log"
local_memstat_log_file: "{{ local_output_dir }}/{{ memstat_log_filename }}"
remote_memstat_log_file: "{{ remote_output_dir }}/{{ memstat_log_filename }}"

iostat_pid_file: "{{ remote_pid_files_dir }}/iostat.pid"
iostat_log_filename: "iostat.log"
local_iostat_log_file: "{{ local_output_dir }}/{{ iostat_log_filename }}"
remote_iostat_log_file: "{{ remote_output_dir }}/{{ iostat_log_filename }}"

pidstat_pid_file: "{{ remote_pid_files_dir }}/pidstat.pid"
pidstat_log_filename: "pidstat.log"
local_pidstat_log_file: "{{ local_output_dir }}/{{ pidstat_log_filename }}"
remote_pidstat_log_file: "{{ remote_output_dir }}/{{ pidstat_log_filename }}"

blkstat_log_dirname: "blkstat_{{ phase }}_round{{ cur_round }}"
remote_blkstat_log_dir: "{{ remote_output_dir }}/{{ blkstat_log_dirname }}"
# See parameter format in module archive for all the available formats
#   https://docs.ansible.com/ansible/latest/modules/archive_module.html
blkstat_archive_format: gz
remote_blkstat_log_archive: "{{ remote_blkstat_log_dir }}.{{ blkstat_archive_format }}"
blkstat_text_filename: "blkstat_{{ phase }}_round{{ cur_round }}_{{ event }}.log"
remote_blkstat_text_file: "{{ remote_output_dir }}/{{ blkstat_text_filename }}"
blkstat_bin_filename: "blkstat_{{ phase }}_round{{ cur_round }}_{{ event }}.bin"
remote_blkstat_bin_file: "{{ remote_output_dir }}/{{ blkstat_bin_filename }}"

ioszdist_log_filename: "ioszdist_{{ phase }}_round{{ cur_round }}.log"
remote_ioszdist_log_file: "{{ remote_output_dir }}/{{ ioszdist_log_filename }}"
