---
local_tmp_data_dir: "{{ inventory_dir }}/tmp/data"

fio_bin: "{{ fio_dir }}/fio"

device_mountpoint: /mnt/{{ device_name }}
rocksdb_data_dir: "{{ device_mountpoint }}/{{ rocksdb_data_dirname }}"

# Since the YCSB RocksDB binding just combines all the fields into a single
# byte array as the value. Reducing the field counts helps to free up more CPU
# resources for the I/O path.
fieldcount: 1

# (DO NOT CHANGE) Use the last x number of values to detect steady state.
measurement_window_size: 3

perf_stats_report_interval_in_secs: 3

single_task_wait_duration: "{{ 60 * 60 * 12 }}"
retry_delay_30_secs: 30

local_output_dir: "{{ inventory_dir }}/analysis/data/ycsb/{{ inventory_hostname }}/{{ device_name }}/output_{{ cur_workload }}"
remote_data_dir: "{{ workdir }}/data/{{ device_name }}"
remote_output_dir: "{{ remote_data_dir }}/output_{{ cur_workload }}"
remote_nohup_output_dir: "{{ remote_data_dir }}/nohup_out"

local_rocksdb_log_file: "{{ local_output_dir }}/LOG_{{ phase }}_round{{ cur_round }}"

rocksdb_remote_input_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"

hdparm_id_info_filename: hdparm_id_info
remote_hdparm_id_info_file: "{{ remote_output_dir }}/{{ hdparm_id_info_filename }}"
local_hdparm_id_info_file: "{{ local_output_dir }}/{{ hdparm_id_info_filename }}"

remote_scripts_dir: "{{ runtimes_dir }}/scripts"
device_purge_script_filename: blkerasediscard.sh
io_accounting_script_filename: io_accounting.sh

wipc_job_filename: wipc.fio
remote_wipc_job_file: "{{ remote_output_dir }}/{{ wipc_job_filename }}"
local_wipc_job_file: "{{ local_output_dir }}/{{ wipc_job_filename }}"

wipc_output_filename: wipc_round{{ cur_round }}.json
local_wipc_output_file: "{{ local_output_dir }}/{{ wipc_output_filename }}"
remote_wipc_output_file: "{{ remote_output_dir }}/{{ wipc_output_filename }}"

ycsb_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"

ycsb_load_filename: "load_round{{ cur_round }}.dat"
ycsb_load_output_file: "{{ local_output_dir }}/{{ ycsb_load_filename }}"

ycsb_transactions_filename: "transactions_round{{ cur_round }}.dat"
ycsb_transactions_output_file: "{{ local_output_dir }}/{{ ycsb_transactions_filename }}"

remote_pid_files_dir: "{{ runtimes_dir }}/pid_files/{{ device_name }}"
local_pid_files_dir: "{{ runtimes_dir }}/pid_files/{{ inventory_hostname }}/{{ device_name }}"

cpustat_pid_file: "{{ remote_pid_files_dir }}/cpustat.pid"
cpustat_log_filename: "cpustat.log"
local_cpustat_log_file: "{{ local_output_dir }}/{{ cpustat_log_filename }}"
remote_cpustat_log_file: "{{ remote_output_dir }}/{{ cpustat_log_filename }}"

memstat_pid_file: "{{ remote_pid_files_dir }}/memstat.pid"
memstat_log_filename: "memstat.log"
local_memstat_log_file: "{{ local_output_dir }}/{{ memstat_log_filename }}"
remote_memstat_log_file: "{{ remote_output_dir }}/{{ memstat_log_filename }}"

iostat_pid_file: "{{ remote_pid_files_dir }}/iostat.pid"
iostat_log_filename: "iostat.log"
local_iostat_log_file: "{{ local_output_dir }}/{{ iostat_log_filename }}"
remote_iostat_log_file: "{{ remote_output_dir }}/{{ iostat_log_filename }}"

pidstat_pid_file: "{{ remote_pid_files_dir }}/pidstat.pid"
pidstat_log_filename: "pidstat.log"
local_pidstat_log_file: "{{ local_output_dir }}/{{ pidstat_log_filename }}"
remote_pidstat_log_file: "{{ remote_output_dir }}/{{ pidstat_log_filename }}"

purge_device_pid_file: "{{ remote_pid_files_dir }}/purge_device.pid"
wipc_pid_file: "{{ remote_pid_files_dir }}/wipc.pid"
rocksdb_pid_file: "{{ remote_pid_files_dir }}/rocksdb.pid"
ycsb_load_pid_file: "{{ local_pid_files_dir }}/ycsb_load.pid"
ycsb_transactions_pid_file: "{{ local_pid_files_dir }}/ycsb_transactions.pid"

io_accounting_filename: "io_accounting_round{{ cur_round }}.log"
local_io_accounting_file: "{{ local_output_dir }}/{{ io_accounting_filename }}"
remote_io_accounting_file: "{{ remote_output_dir }}/{{ io_accounting_filename }}"
