---
fio_bin: "{{ fio_dir }}/fio"

rocksdb_data_dir: "{{ device_mountpoint }}/{{ rocksdb_data_dirname }}"

# Since the YCSB RocksDB binding just combines all the fields into a single
# byte array as the value. Reducing the field counts helps to free up more CPU
# resources for the I/O path.
fieldcount: 1

# (DO NOT CHANGE) Use the last x number of values to detect steady state.
measurement_window_size: 3

perf_stats_report_interval_in_secs: 3

# Performance monitoring commands
perf_cpustat_command: mpstat -P ALL {{ perf_stats_report_interval_in_secs }}

# we may need to check the values of si and so. Because if these numbers are non-zero, you’re out of memory.
perf_memstat_command: vmstat --one-header --wide --unit K --timestamp {{ perf_stats_report_interval_in_secs }}

perf_iostat_command: iostat -dktxyzH -g {{ device_name }} {{ device_fullname }} {{ perf_stats_report_interval_in_secs }}
perf_pidstat_command: pidstat -G java -ult {{ perf_stats_report_interval_in_secs }}

perf_netstat_command: sar -n DEV {{ perf_stats_report_interval_in_secs }}

single_task_wait_duration: "{{ 60 * 60 * 12 }}"
retry_delay_30_secs: 30

local_output_inventory: "{{ inventory_dir }}/analysis/data/ycsb/{{ current_host | default(inventory_hostname) }}"
local_output_dir: "{{ local_output_inventory }}/{{ device_name }}/output_{{ cur_workload }}"
remote_output_dir: "{{ remote_device_data_dir }}/output_{{ cur_workload }}"

local_rocksdb_log_file: "{{ local_output_dir }}/LOG_{{ phase }}_round{{ cur_round }}"

rocksdb_remote_input_options_file: "{{ remote_output_dir }}/{{ rocksdb_options_file | basename }}"

device_id_info_filename: device_id_info
remote_device_id_info_file: "{{ remote_output_dir }}/{{ device_id_info_filename }}"
local_device_id_info_file: "{{ local_output_dir }}/{{ device_id_info_filename }}"

io_accounting_script_filename: io_accounting.sh

wipc_job_filename: wipc.fio
remote_wipc_job_file: "{{ remote_output_dir }}/{{ wipc_job_filename }}"
local_wipc_job_file: "{{ local_output_dir }}/{{ wipc_job_filename }}"

wipc_output_filename: wipc_round{{ cur_round }}.json
local_wipc_output_file: "{{ local_output_dir }}/{{ wipc_output_filename }}"
remote_wipc_output_file: "{{ remote_output_dir }}/{{ wipc_output_filename }}"

ycsb_workload_file: "{{ local_output_dir }}/{{ cur_workload }}"

ycsb_load_filename: "load_round{{ cur_round }}.dat"
ycsb_load_output_file: "{{ local_output_dir }}/{{ ycsb_load_filename }}"

ycsb_transactions_filename: "transactions_round{{ cur_round }}.dat"
ycsb_transactions_output_file: "{{ local_output_dir }}/{{ ycsb_transactions_filename }}"

local_sys_usage_info_dir: "{{ local_output_dir }}/sys_usage"
remote_sys_usage_info_dir: "{{ remote_output_dir }}/sys_usage"

ycsb_sys_usage_info_dir: "{{ local_sys_usage_info_dir }}/ycsb"
rocksdb_sys_usage_info_dir: "{{ remote_sys_usage_info_dir }}/rocksdb"
storage_sys_usage_info_dir: "{{ remote_sys_usage_info_dir }}/storage"
local_storage_sys_usage_info_dir: "{{ local_sys_usage_info_dir }}/storage"

cpustat_pid_filename: "cpustat.pid"
rocksdb_cpustat_pid_file: "{{ remote_pid_files_dir }}/{{ cpustat_pid_filename }}"
ycsb_cpustat_pid_file: "{{ local_pid_files_dir }}/{{ cpustat_pid_filename }}"

cpustat_log_filename: "cpustat.log"
rocksdb_cpustat_log_file: "{{ rocksdb_sys_usage_info_dir }}/{{ cpustat_log_filename }}"
ycsb_cpustat_log_file: "{{ ycsb_sys_usage_info_dir }}/{{ cpustat_log_filename }}"

memstat_pid_filename: "memstat.pid"
rocksdb_memstat_pid_file: "{{ remote_pid_files_dir }}/{{ memstat_pid_filename }}"
ycsb_memstat_pid_file: "{{ local_pid_files_dir }}/{{ memstat_pid_filename }}"

memstat_log_filename: "memstat.log"
rocksdb_memstat_log_file: "{{ rocksdb_sys_usage_info_dir }}/{{ memstat_log_filename }}"
ycsb_memstat_log_file: "{{ ycsb_sys_usage_info_dir }}/{{ memstat_log_filename }}"

iostat_pid_filename: "iostat.pid"
rocksdb_iostat_pid_file: "{{ remote_pid_files_dir }}/{{ iostat_pid_filename }}"

iostat_log_filename: "iostat.log"
rocksdb_iostat_log_file: "{{ rocksdb_sys_usage_info_dir }}/{{ iostat_log_filename }}"

pidstat_pid_filename: "pidstat.pid"
rocksdb_pidstat_pid_file: "{{ remote_pid_files_dir }}/{{ pidstat_pid_filename }}"
ycsb_pidstat_pid_file: "{{ local_pid_files_dir }}/{{ pidstat_pid_filename }}"

pidstat_log_filename: "pidstat.log"
rocksdb_pidstat_log_file: "{{ rocksdb_sys_usage_info_dir }}/{{ pidstat_log_filename }}"
ycsb_pidstat_log_file: "{{ ycsb_sys_usage_info_dir }}/{{ pidstat_log_filename }}"

netstat_pid_filename: "netstat.pid"
rocksdb_netstat_pid_file: "{{ remote_pid_files_dir }}/{{ netstat_pid_filename }}"
ycsb_netstat_pid_file: "{{ local_pid_files_dir }}/{{ netstat_pid_filename }}"

netstat_log_filename: "netstat.log"
rocksdb_netstat_log_file: "{{ rocksdb_sys_usage_info_dir }}/{{ netstat_log_filename }}"
ycsb_netstat_log_file: "{{ ycsb_sys_usage_info_dir }}/{{ netstat_log_filename }}"

purge_device_pid_file: "{{ remote_pid_files_dir }}/purge_device.pid"
wipc_pid_file: "{{ remote_pid_files_dir }}/wipc.pid"
rocksdb_pid_file: "{{ remote_pid_files_dir }}/rocksdb.pid"
ycsb_load_pid_file: "{{ local_pid_files_dir }}/ycsb_load.pid"
ycsb_transactions_pid_file: "{{ local_pid_files_dir }}/ycsb_transactions.pid"

io_accounting_filename: "io_accounting_round{{ cur_round }}.log"
local_io_accounting_file: "{{ local_output_dir }}/{{ io_accounting_filename }}"
remote_io_accounting_file: "{{ remote_output_dir }}/{{ io_accounting_filename }}"
