---
# (DO NOT CHANGE) Use the last x number of values for steady state detection.
measurement_window_size: 3

local_rocksdb_log_file: '{{ local_output_device_dir }}/RocksDB_LOG_{{ phase }}_round{{ cur_round }}'

wipc_output_filename: wipc_round{{ cur_round }}.json
local_wipc_output_file: '{{ local_output_device_dir }}/{{ wipc_output_filename }}'
remote_wipc_output_file: '{{ remote_output_device_dir }}/{{ wipc_output_filename }}'

ycsb_load_filename: 'ycsb_load@{{ inventory_hostname }}:{{ device_name }}_round{{ cur_round }}.dat'
ycsb_load_output_file: '{{ local_output_dir }}/{{ ycsb_load_filename }}'

ycsb_transactions_filename: 'ycsb_transactions@{{ inventory_hostname }}:{{ device_name }}_round{{ cur_round }}.dat'
ycsb_transactions_output_file: '{{ local_output_dir }}/{{ ycsb_transactions_filename }}'

io_accounting_filename: 'io_accounting_round{{ cur_round }}.log'
local_io_accounting_file: '{{ local_output_device_dir }}/{{ io_accounting_filename }}'
remote_io_accounting_file: '{{ remote_output_device_dir }}/{{ io_accounting_filename }}'

# flag 'b' stands for the stats before executing the workload
# flag 'a' stands for the stats after executing the workload
device_stats_filename: 'device_stats_round{{ cur_round }}_{{ flag }}.log'

local_device_stats_file: '{{ local_output_device_dir }}/{{ device_stats_filename }}'
remote_device_stats_file: '{{ remote_output_device_dir }}/{{ device_stats_filename }}'

device_stats_command: grep {{ device_name }} /proc/diskstats
