---
- name: ({{ notes }}) start to collect {{ system }} performance statistics
  # we use stdbuf to turn off buffering of the output redirection.
  #   https://linux.die.net/man/1/stdbuf
  #   https://stackoverflow.com/a/1429973
  shell: >
    nohup stdbuf -oL -eL {{ perf_stat.command }} < /dev/null > {{ sys_usage_log_file }} 2>&1 &
    echo $! > {{ sys_usage_pid_file }}
  environment:
    S_TIME_FORMAT: ISO
  vars:
    device_name: "{{ device_fullname | basename }}"
    performance_stat_name: "{{ perf_stat.name }}"
  loop: "{{ performance_stats }}"
  loop_control:
    loop_var: perf_stat
  when: perf_stat.name != perf_stat_name_is_not | default("")
  changed_when: True
...
