---
- include_tasks: performance_stats/stop.yml
  vars:
    system: ycsb
    sys_usage_pid_files_dir: "{{ remote_pid_files_dir }}"
  loop: "{{ device_fullnames }}"
  loop_control:
    loop_var: device_fullname

- include_tasks: performance_stats/local.yml
  vars:
    action_filename: stop.yml
    system: local
    sys_usage_pid_files_dir: "{{ local_pid_files_dir }}"
  loop: "{{ device_fullnames }}"
  loop_control:
    loop_var: device_fullname
...
