---
- hosts: all
  any_errors_fatal: true
  vars:
    core_workloads: [ 'workloada', 'workloadb', 'workloadc', 'workloadd', 'workloade', 'workloadf' ]
    ycsb_dir: "{{ workdir }}/YCSB"
    maven_dir: "{{ workdir }}/apache-maven-{{ maven_version }}"
  pre_tasks:
    - name: collect the run workloads
      set_fact:
        run_workloads: "{{ ycsb_run_workloads.split(',') }}"
    - name: retrieve the stats of user-defined workload parameter files
      stat:
        follow: yes
        get_attributes: no
        path: "{{ item }}"
      when: item not in core_workloads
      loop: "{{ run_workloads }}"
      register: stat_res
    - name: verify the paths of user-defined workload parameter files
      debug:
        msg: >
          Please verify the path of the workload parameter file {{ item.item }}
      when: item.stat is defined and not item.stat.exists
      failed_when: item.stat is defined and not item.stat.exists
      loop: "{{ stat_res.results }}"

    - name: get the source device of mountpoint {{ mountpoint }}
      command: >
        findmnt --noheadings --output SOURCE --mountpoint {{ mountpoint }}
      register: comm_res
      changed_when: False
      ignore_errors: yes
    - name: save the source device name
      set_fact:
        device_fullname: "{{ comm_res.stdout }}"
    - debug:
        msg: >
          Unable to find the source device of the mountpoint {{ mountpoint }}.
          Please note that the 'mountpoint' has to be the strictly specified
          mountpoint of the device.
      when: device_fullname == ""
      failed_when: device_fullname == ""
  roles:
    - setup
    - role: run
      vars:
        local_tmp_data_dir: "{{ inventory_dir }}/tmp/data"
...
