---
- hosts: all
  any_errors_fatal: true
  tags: [ 'always' ]
  vars:
    core_workloads: [ 'workloada', 'workloadb', 'workloadc', 'workloadd', 'workloade', 'workloadf' ]
    available_workloads: []
    ycsb_dir: "{{ workdir }}/YCSB"
    maven_dir: "{{ workdir }}/apache-maven-{{ maven_version }}"
  pre_tasks:
    - name: collect core and user-defined workloads
      set_fact:
        available_workloads: >
          {% set workload_name = item | basename -%}
          {% if workload_name == 'common' -%}
              {{ available_workloads + core_workloads }}
          {% else -%}
              {{ available_workloads + [ workload_name ] }}
          {% endif -%}
      with_fileglob: "{{ playbook_dir }}/roles/run/templates/*"
    - name: get run workloads
      set_fact:
        run_workloads: "{{ ansible_run_tags | intersect(available_workloads) }}"
    - debug:
        msg: >
          Please specify at least one of workload
          {{ available_workloads }} to run using '--tags'
      when: run_workloads | length == 0
      failed_when: run_workloads | length == 0

    - name: get the source device of mountpoint {{ mountpoint }}
      shell: >
        basename "$(findmnt --noheadings --output SOURCE --mountpoint {{ mountpoint }})"
      register: comm_res
      changed_when: False
    - name: save the source device name
      set_fact:
        device_name: "{{ comm_res.stdout | basename }}"
    - debug:
        msg: >
          Unable to find the source device of the mountpoint {{ mountpoint }}.
          Please note that the 'mountpoint' has to be the strictly specified
          mountpoint of the device.
      when: device_name == ""
      failed_when: device_name == ""
  roles:
    - setup
    - role: run
      vars:
        local_tmp_data_dir: "{{ inventory_dir }}/tmp/data"
        rocksdb_data_dir: "{{ mountpoint }}/{{ rocksdb_data_dirname }}"
        device_stats_command: grep -oP '{{ device_name }}\s+\K.+$' /proc/diskstats
...
