---
- hosts: all
  any_errors_fatal: true
  tags: [ 'always' ]
  vars:
    workloads_dir: "{{ workdir }}/workloads"
  pre_tasks:
    - name: search all available workload parameter files
      set_fact:
        available_workloads: "{{ available_workloads | default([]) + [ item | basename ] }}"
      with_fileglob:
        - "{{ playbook_dir }}/roles/run/templates/workload*"
    - name: collect run workloads
      set_fact:
        run_workloads: "{{ ansible_run_tags | intersect(available_workloads) }}"
    - debug:
        msg: >
          Please specify at least one of workload
          {{ available_workloads }} to run using '--tags'
      when: run_workloads | length == 0
      failed_when: run_workloads | length == 0

    - name: ensure the presence of the remote workloads dir {{ workloads_dir }}
      become: yes
      file:
        owner: "{{ ansible_user }}"
        path: "{{ workloads_dir }}"
        state: directory
  roles:
    - setup
    - run
...
