---
- hosts: all
  any_errors_fatal: true
  vars:
    core_workloads: [ 'workloada', 'workloadb', 'workloadc', 'workloadd', 'workloade', 'workloadf' ]
    ycsb_dir: "{{ workdir }}/YCSB"
    maven_dir: "{{ workdir }}/apache-maven-{{ maven_version }}"
    device_fullname: /dev/{{ device_name }}
  pre_tasks:
    - name: retrieve the stat of block device {{ device_fullname }}
      stat:
        follow: no
        get_attributes: no
        get_checksum: no
        get_md5: no
        get_mime: no
        path: "{{ device_fullname }}"
      register: stat_res
    - name: verify the existence of block device {{ device_fullname }}
      debug:
        msg: >
          Please double check the existence of block device {{ device_fullname }}
      when: stat_res.stat.isblk is not defined or not stat_res.stat.isblk
      failed_when: stat_res.stat.isblk is not defined or not stat_res.stat.isblk

    - name: collect the run workloads
      set_fact:
        run_workloads: "{{ ycsb_run_workloads.split(',') }}"
    - name: retrieve the stats of user-defined workload parameter files
      stat:
        follow: yes
        get_attributes: no
        path: "{{ item }}"
      when: item not in core_workloads
      loop: "{{ run_workloads }}"
      register: stat_res
    - name: verify the paths of user-defined workload parameter files
      debug:
        msg: >
          Please verify the path of the workload parameter file {{ item.item }}
      when: item.stat is defined and not item.stat.exists
      failed_when: item.stat is defined and not item.stat.exists
      loop: "{{ stat_res.results }}"

  roles:
    - setup
    - role: run
      vars:
        local_tmp_data_dir: "{{ inventory_dir }}/tmp/data"
...
