---
- host: all
  any_errors_fatal: true
  vars:
    rocksdb_dir: "{{ workdir }}/rocksdb-{{ rocksdb_version }}"
    rocksdbjni_src: "{{ rocksdb_dir }}/java/target/rocksdbjni-{{ rocksdb_version }}-linux64.jar"
    rocksdbjni_dest_dir: "{{ ansible_user_dir }}/.m2/repository/org/rocksdb/rocksdbjni/{{ rocksdb_version }}"
    rocksdbjni_dest_pom: "{{ rocksdbjni_dest_dir }}/rocksdbjni-{{ rocksdb_version }}.pom"
    ycsb_dir: "{{ workdir }}/YCSB"
    maven_dir: "{{ workdir }}/apache-maven-{{ maven_version }}"
  tasks:
    - name: download RocksDB source code
      unarchive:
        creates: "{{ rocksdb_dir }}"
        dest: "{{ workdir }}"
        keep_newer: no
        remote_src: yes
        src: https://codeload.github.com/facebook/rocksdb/tar.gz/v{{ rocksdb_version }}
    - name: add WebUpd8 Oracle Java PPA
      become: yes
      apt_repository:
        repo: ppa:webupd8team/java
        state: present
        update_cache: yes
    - name: install dependent apt packages
      become: yes
      apt:
        autoclean: yes
        install_recommends: no
        name:
          - gcc
          - libgflags-dev
          - libsnappy-dev
          - zlib1g-dev
          - libbz2-dev
          - liblz4-dev
          - libzstd-dev
          - oracle-java8-installer
        state: present
        update_cache: yes
    - name: build RocksJava
      command: >
        JAVA_HOME=/usr/lib/jvm/java-8-oracle make -j{{ ansible_processor_vcpus - 1 }} rocksdbjavastatic
      args:
        chdir: "{{ rocksdb_dir }}"
        creates: "{{ rocksdbjni_src }}"
    - name: ensure the presence of rocksdbjni dir in maven repo
      file:
        path: "{{ rocksdbjni_dest_dir }}"
        state: directory
    - name: copy rocksdbjni jar to maven repository
      copy:
        dest: "{{ rocksdbjni_dest_dir }}/rocksdbjni-{{ rocksdb_version }}.jar"
        force: yes
        remote_src: yes
        src: "{{ rocksdbjni_src }}"
    - name: copy rocksdbjni pom to maven repository
      copy:
        dest: "{{ rocksdbjni_dest_pom }}"
        force: yes
        remote_src: yes
        src: "{{ rocksdb_dir }}/java/rocksjni.pom"
    - name: update the version of the rocksdbjni-{{ rocksdb_version }}.pom
      lineinfile:
        backrefs: yes
        create: no
        line: '\1{{ rocksdb_version }}\2'
        path: "{{ rocksdbjni_dest_pom }}"
        regexp: '(^\\s+<version>)\-(</version>$)'
        state: present
    - name: clone YCSB
      git:
        bare: no
        clone: yes
        depth: 1
        dest: "{{ ycsb_dir }}"
        force: yes
        repo: https://github.com/ljishen/YCSB.git
        update: yes
    - name: update RocksDB version in YCSB
      lineinfile:
        backrefs: yes
        create: no
        line: '\1{{ rocksdb_version }}\2'
        path: "{{ ycsb_dir }}/pom.xml"
        regexp: '(^\\s+<rocksdb\.version>)[\\d.]+(</rocksdb\.version>$)'
        state: present
    - name: download Apache Maven
      unarchive:
        creates: "{{ maven_dir }}"
        dest: "{{ workdir }}"
        keep_newer: no
        remote_src: yes
        src: http://mirrors.sorengard.com/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    - name: build RocksDB YCSB binding
      command: >
        {{ maven_dir }}/bin/mvn -pl com.yahoo.ycsb:rocksdb-binding -am clean package
      args:
        chdir: "{{ ycsb_dir }}"
        creates: "{{ ycsb_dir }}/rocksdb/target"
...
