---
- name: check if JDK installed
  command: javac -version
  failed_when: False
  register: comm_res
  changed_when: False

- name: install OpenJDK
  become: yes
  apt:
    cache_valid_time: '{{ 60 * 60 * 24 }}' # cache is valid in a day
    install_recommends: no
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  when: comm_res.rc != 0

- name: install Apache Maven
  unarchive:
    creates: '{{ maven_dir }}'
    dest: '{{ software_dir }}'
    keep_newer: no
    owner: '{{ ansible_user }}'
    remote_src: yes
    src: http://mirrors.ibiblio.org/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
